<?php
/**
 * Plugin Name: Schema Markup Adder
 * Description: Injects comprehensive schema markup (LocalBusiness, Service, Review/AggregateRating, ContactPoint, OpeningHoursSpecification, SocialProfile, FAQPage, BreadcrumbList) and removes duplicate JSON‑LD.
 * Version: 1.2.0
 * Author: Antigravity AI (generated by Claude)
 * License: GPL2
 */

if (!defined('ABSPATH')) {
    exit; // Prevent direct access
}

/** -------------------------------------------------------------------
 * Phase 1: Remove any existing JSON‑LD blocks to avoid duplicates.
 * ------------------------------------------------------------------- */
function sma_remove_duplicate_schema($content) {
    // Guard: DOMDocument::loadHTML() throws a fatal ValueError in PHP 8 when
    // passed an empty string. This function is also (incorrectly) hooked to
    // wp_head, which passes no content, so bail out on empty/non-string input.
    if ( ! is_string( $content ) || trim( $content ) === '' ) {
        return $content;
    }
    libxml_use_internal_errors(true);
    $doc = new DOMDocument();
    $doc->loadHTML(mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8'));
    $scripts = $doc->getElementsByTagName('script');
    $toRemove = [];
    foreach ($scripts as $script) {
        if ($script->getAttribute('type') === 'application/ld+json') {
            $toRemove[] = $script;
        }
    }
    foreach ($toRemove as $node) {
        $node->parentNode->removeChild($node);
    }
    $clean = $doc->saveHTML();
    libxml_clear_errors();
    return $clean;
}
add_filter('the_content', 'sma_remove_duplicate_schema', 1);
add_filter('wp_head', 'sma_remove_duplicate_schema', 1);

/** -------------------------------------------------------------------
 * Phase 2: LocalBusiness schema – core business information.
 * ------------------------------------------------------------------- */
function sma_localbusiness_schema() {
    // ----- UPDATE THESE VALUES WITH YOUR ACTUAL INFORMATION -----
    $address = [
        '@type'           => 'PostalAddress',
        'streetAddress'   => 'Your Street, Your Area', // e.g. "123 Main St, Sector 5"
        'addressLocality' => 'Goa',
        'addressRegion'   => 'Goa',
        'postalCode'      => '403001',
        'addressCountry'  => 'IN',
    ];
    $geo = [
        '@type'    => 'GeoCoordinates',
        'latitude'  => '15.2993',   // from Google Maps URL
        'longitude' => '74.1240',   // from Google Maps URL
    ];
    $phone = '+91-XXXXXXXXXX'; // <-- use the same number for phone & WhatsApp
    $email = 'info@sanctify.in';
    // ------------------------------------------------------------
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'LocalBusiness',
        'name'     => 'Sanctify',
        'url'      => home_url(),
        'logo'     => get_theme_mod('custom_logo') ? wp_get_attachment_url(get_theme_mod('custom_logo')) : '',
        'address'  => $address,
        'geo'      => $geo,
        'telephone'=> $phone,
        'email'    => $email,
        // Opening hours will be added in a separate schema block (phase 4).
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_localbusiness_schema');

/** -------------------------------------------------------------------
 * Phase 3: Service schema – list each service you offer.
 * ------------------------------------------------------------------- */
function sma_service_schema() {
    // Expect a custom post type "service" with title, content, optional "price" custom field.
    $services = get_posts([
        'post_type'      => 'service',
        'posts_per_page' => -1,
        'post_status'    => 'publish',
    ]);
    if (empty($services)) {
        return;
    }
    $serviceItems = [];
    foreach ($services as $svc) {
        $offer = null;
        $price = get_post_meta($svc->ID, 'price', true);
        if ($price) {
            $offer = [
                '@type' => 'Offer',
                'price' => $price,
                'priceCurrency' => 'INR',
            ];
        }
        $serviceItems[] = [
            '@type'       => 'Service',
            'name'        => get_the_title($svc),
            'description' => wp_strip_all_tags(apply_filters('the_content', $svc->post_content)),
            'offers'      => $offer,
        ];
    }
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'Service',
        'provider' => [
            '@type' => 'LocalBusiness',
            'name'  => 'Sanctify',
        ],
        'hasOfferCatalog' => [
            '@type' => 'OfferCatalog',
            'itemListElement' => $serviceItems,
        ],
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_service_schema');

/** -------------------------------------------------------------------
 * Phase 4: Review / AggregateRating schema – customer feedback.
 * ------------------------------------------------------------------- */
function sma_review_schema() {
    // Expect a custom post type "review" with a numeric meta field "rating" (1‑5).
    $reviews = get_posts([
        'post_type'      => 'review',
        'posts_per_page' => -1,
        'post_status'    => 'publish',
    ]);
    if (empty($reviews)) {
        return;
    }
    $reviewItems = [];
    $totalRating = 0;
    $count = 0;
    foreach ($reviews as $rev) {
        $rating = (float) get_post_meta($rev->ID, 'rating', true);
        if ($rating) {
            $reviewItems[] = [
                '@type'         => 'Review',
                'author'        => get_the_author_meta('display_name', $rev->post_author),
                'datePublished' => get_the_date('c', $rev),
                'reviewBody'    => wp_strip_all_tags(apply_filters('the_content', $rev->post_content)),
                'reviewRating'  => [
                    '@type'       => 'Rating',
                    'ratingValue' => $rating,
                    'bestRating'  => 5,
                    'worstRating' => 1,
                ],
            ];
            $totalRating += $rating;
            $count++;
        }
    }
    $aggregate = [];
    if ($count > 0) {
        $aggregate = [
            '@type'       => 'AggregateRating',
            'ratingValue' => round($totalRating / $count, 1),
            'reviewCount' => $count,
            'bestRating'  => 5,
            'worstRating' => 1,
        ];
    }
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'Product', // Using Product as a container for reviews.
        'name'     => 'Sanctify Services',
        'review'   => $reviewItems,
    ];
    if (!empty($aggregate)) {
        $data['aggregateRating'] = $aggregate;
    }
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_review_schema');

/** -------------------------------------------------------------------
 * Phase 5: ContactPoint schema – phone, email, WhatsApp.
 * ------------------------------------------------------------------- */
function sma_contactpoint_schema() {
    // Use the same phone number for regular calls and WhatsApp.
    $phone = '+91-XXXXXXXXXX'; // <-- replace with your actual number (include country code)
    $email = 'info@sanctify.in'; // <-- replace with your email
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'ContactPoint',
        'telephone'        => $phone,
        'email'            => $email,
        'contactType'      => 'customer service',
        'areaServed'       => 'IN',
        'availableLanguage'=> ['English','Hindi'],
        // Show that this number is also reachable via WhatsApp.
        'contactOption'    => 'WhatsApp',
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_contactpoint_schema');

/** -------------------------------------------------------------------
 * Phase 6: OpeningHoursSpecification – detailed schedule.
 * ------------------------------------------------------------------- */
function sma_openinghours_schema() {
    $hours = [
        [
            '@type' => 'OpeningHoursSpecification',
            'dayOfWeek' => ['Monday','Tuesday','Wednesday','Thursday','Friday'],
            'opens' => '09:00',
            'closes' => '18:00',
        ],
        [
            '@type' => 'OpeningHoursSpecification',
            'dayOfWeek' => ['Saturday'],
            'opens' => '10:00',
            'closes' => '15:00',
        ],
        [
            '@type' => 'OpeningHoursSpecification',
            'dayOfWeek' => ['Sunday'],
            'opens' => 'Closed',
            'closes' => 'Closed',
        ],
    ];
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'LocalBusiness',
        'openingHoursSpecification' => $hours,
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_openinghours_schema');

/** -------------------------------------------------------------------
 * Phase 7: SocialProfile schema – your social media URLs.
 * ------------------------------------------------------------------- */
function sma_socialprofile_schema() {
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'Organization',
        'url'      => home_url(),
        // Replace the URLs below with your actual profiles.
        'sameAs'   => [
            'https://www.facebook.com/sanctifygoa/',
            'https://www.instagram.com/sanctifygoa/',
            'https://in.linkedin.com/company/sanctify',
            'https://www.youtube.com/c/SanctifyGoa/',
        ],
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_socialprofile_schema');

/** -------------------------------------------------------------------
 * Phase 8: FAQPage schema – pulls from a custom post type "faq".
 * ------------------------------------------------------------------- */
function sma_faq_schema() {
    $faqs = get_posts([
        'post_type'      => 'faq',
        'posts_per_page' => -1,
        'post_status'    => 'publish',
    ]);
    if (empty($faqs)) {
        return;
    }
    $questions = [];
    foreach ($faqs as $faq) {
        $questions[] = [
            '@type'          => 'Question',
            'name'           => get_the_title($faq),
            'acceptedAnswer' => [
                '@type' => 'Answer',
                'text'  => wp_strip_all_tags(apply_filters('the_content', $faq->post_content)),
            ],
        ];
    }
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'FAQPage',
        'mainEntity' => $questions,
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_faq_schema');

/** -------------------------------------------------------------------
 * Phase 9: BreadcrumbList schema – for better navigation in SERPs.
 * ------------------------------------------------------------------- */
function sma_breadcrumb_schema() {
    if (!is_singular()) {
        return;
    }
    $post = get_queried_object();
    $crumbs = [];
    $crumbs[] = [
        '@type'    => 'ListItem',
        'position' => 1,
        'name'     => get_bloginfo('name'),
        'item'     => home_url('/')
    ];
    if (is_category() || is_tax()) {
        $term = get_queried_object();
        $crumbs[] = [
            '@type'    => 'ListItem',
            'position' => 2,
            'name'     => $term->name,
            'item'     => get_term_link($term)
        ];
    } else {
        $crumbs[] = [
            '@type'    => 'ListItem',
            'position' => 2,
            'name'     => $post->post_title,
            'item'     => get_permalink($post)
        ];
    }
    $data = [
        '@context' => 'https://schema.org',
        '@type'    => 'BreadcrumbList',
        'itemListElement' => $crumbs,
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}
add_action('wp_head', 'sma_breadcrumb_schema');

/** End of Schema Markup Adder plugin */
?>